name: Python Lint

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 .

      - name: Install dependencies
        run: |
          pip install nose
          pip install -r requirements.txt || true  # Optional if you use it

      - name: Run Nose tests
        run: nosetests
